---
collections:
  - name: operator_sdk.util
  # Kubernetes API access (nodes, endpoint slices, jobs, secrets)
  - name: kubernetes.core
  # AWS EC2 ENI / VPC management
  - name: amazon.aws
  # AWS module dependencies
  - name: community.aws
  - name: cloud.common
