---
# Example proxy workload Pod. Once scheduled onto a proxy node, the operator
# will patch this Pod with cxl.io/egress-gw=<node-hash> to bind it to the
# correct node-local CiliumEgressGatewayPolicy.
apiVersion: v1
kind: Pod
metadata:
  name: haproxy-remote-eni
  labels:
    app.kubernetes.io/name: haproxy-remote-eni
spec:
  restartPolicy: Always
  containers:
    - name: haproxy
      image: haproxy:3.1
      ports:
        - containerPort: 8080
          name: http